{
    "openapi" : "3.1.0",
    "info" : {
      "description" : "Welcome to the Cloud Foundry V3 API docs! Version 3 adds support for several key features:\n\n- Running one-off tasks on Cloud Foundry\n- Applications consisting of several processes via a Procfile\n- Direct access to application packages and droplets\n- Changing application source code without stopping the app via deployments",
      "license" : {
        "name" : "Apache 2.0"
      },
      "title" : "Cloud Foundry V3 API",
      "version" : "3.151.0"
    },
    "servers" : [ {
      "url" : "https://api.cf.eu12.hana.ondemand.com/"
    } ],
    "tags" : [ {
      "description" : "Endpoints specific to administrative users.",
      "name" : "Admin"
    }, {
      "description" : "Endpoints related to application management and configuration.",
      "name" : "Apps"
    }, {
      "description" : "Endpoints for managing app functionalities.",
      "name" : "App Features"
    }, {
      "description" : "Endpoints for tracking changes in application usage.",
      "name" : "App Usage Events"
    }, {
      "description" : "Endpoints for monitoring user and system actions on resources.",
      "name" : "Audit Events"
    }, {
      "description" : "Endpoints for managing the staging process of application packages.",
      "name" : "Builds"
    }, {
      "description" : "Endpoints related to buildpacks, which are used for transforming packages into executable applications.",
      "name" : "Buildpacks"
    }, {
      "description" : "Endpoints for managing application updates with zero downtime.",
      "name" : "Deployments"
    }, {
      "description" : "Endpoints for managing domain names used for application routes.",
      "name" : "Domains"
    }, {
      "description" : "Endpoints related to droplets, which are the results of staging an application package.",
      "name" : "Droplets"
    }, {
      "description" : "Endpoints for managing environment variables across all apps.",
      "name" : "Environment Variable Groups"
    }, {
      "description" : "Endpoints for enabling or disabling API functionalities.",
      "name" : "Feature Flags"
    }, {
      "description" : "Endpoints for retrieving Cloud Controller configuration information.",
      "name" : "Info"
    }, {
      "description" : "Endpoints for managing dedicated resource pools for apps.",
      "name" : "Isolation Segments"
    }, {
      "description" : "Endpoints related to asynchronous actions performed by the platform.",
      "name" : "Jobs"
    }, {
      "description" : "Endpoints for applying bulk configurations to apps and their processes.",
      "name" : "Manifests"
    }, {
      "description" : "Endpoints related to development accounts owned and used by collaborators.",
      "name" : "Organizations"
    }, {
      "description" : "Endpoints for managing named sets of resource usage quotas.",
      "name" : "Organization Quotas"
    }, {
      "description" : "Endpoints related to application source code.",
      "name" : "Packages"
    }, {
      "description" : "Endpoints for defining runnable units of an app.",
      "name" : "Processes"
    }, {
      "description" : "Endpoint for matching resource SHA-1/file size pairs against the Cloud Controller cache.",
      "name" : "Resource Matches"
    }, {
      "description" : "Endpoints related to specific versions of application code and configuration.",
      "name" : "Revisions"
    }, {
      "description" : "Endpoints for managing network traffic distribution based on various matching criteria.",
      "name" : "Routes"
    }, {
      "description" : "Endpoints for controlling access to resources in organizations and spaces.",
      "name" : "Roles"
    }, {
      "description" : "Endpoints for managing collections of egress traffic rules.",
      "name" : "Security Groups"
    }, {
      "description" : "Endpoints for managing the lifecycle of services.",
      "name" : "Service Brokers"
    }, {
      "description" : "Endpoints related to services offered by service brokers.",
      "name" : "Service Offerings"
    }, {
      "description" : "Endpoints related to service plans offered by a service offering.",
      "name" : "Service Plans"
    }, {
      "description" : "Endpoints for managing access to given service plans and their service offering.",
      "name" : "Service Plan Visibility"
    }, {
      "description" : "Endpoints for managing instantiations of a service.",
      "name" : "Service Instances"
    }, {
      "description" : "Endpoints for making service instance connection details available.",
      "name" : "Service Credential Bindings"
    }, {
      "description" : "Endpoints for managing relations between a service instance and a route.",
      "name" : "Service Route Bindings"
    }, {
      "description" : "Endpoints for tracking changes in service usage.",
      "name" : "Service Usage Events"
    }, {
      "description" : "Endpoints for managing additional operating system processes run in the same container as a process.",
      "name" : "Sidecars"
    }, {
      "description" : "Endpoints for managing spaces.",
      "name" : "Spaces"
    }, {
      "description" : "Endpoints for managing optional capabilities of a space.",
      "name" : "Space Features"
    }, {
      "description" : "Endpoints for managing named sets of quotas within an organization.",
      "name" : "Space Quotas"
    }, {
      "description" : "Endpoints for managing stacks that apps will execute in.",
      "name" : "Stacks"
    }, {
      "description" : "Endpoints for managing one-off jobs that are intended to perform a task, stop, and be cleaned up, freeing up resources.",
      "name" : "Tasks"
    }, {
      "description" : "Endpoints for managing users.",
      "name" : "Users"
    }, {
      "name" : "Experimental"
    } ],
    "paths" : {
      "/v3/admin/actions/clear_buildpack_cache" : {
        "post" : {
          "description" : "This endpoint will delete all of the existing buildpack caches in the blobstore. The buildpack cache is used during staging by buildpacks as a way to cache certain resources, e.g. downloaded Ruby gems. An admin who wants to decrease the size of their blobstore could use this endpoint to delete unnecessary blobs.\n\n__Permitted Roles:__:\n  * Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "tags" : [ "Admin" ]
        }
      },
      "/v3/apps" : {
        "get" : {
          "description" : "Retrieve all apps the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List apps",
          "tags" : [ "Apps" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete an app",
          "tags" : [ "Apps" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an app",
          "tags" : [ "Apps" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/droplets/current" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get current droplet",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/relationships/current_droplet" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get current droplet association for an app",
          "tags" : [ "Apps" ]
        },
        "patch" : {
          "description" : "Set the current droplet for an app. The current droplet is the droplet that the app will use when running.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Set current droplet",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/env" : {
        "get" : {
          "description" : "Retrieve the environment variables that will be provided to an app at runtime. It will include environment variables for Environment Variable Groups and Service Bindings.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter (`system_env_json` redacted)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Get environment for an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/environment_variables" : {
        "get" : {
          "description" : "Retrieve the environment variables that are associated with the given app. For the entire list of environment variables that will be available to the app at runtime, see the env endpoint.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Get environment variables for an app",
          "tags" : [ "Apps" ]
        },
        "patch" : {
          "description" : "Update the environment variables associated with the given app. The variables given in the request will be merged with the existing app environment variables. Any requested variables with a value of null will be removed from the app. Environment variable names may not start with `VCAP_.PORT` is not a valid environment variable.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update environment variables for an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/permissions" : {
        "get" : {
          "description" : "Get the current user’s permissions for the given app. If a user can see an app, then they can see its basic data.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get permissions for an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/ssh_enabled" : {
        "get" : {
          "description" : "Returns if an application’s runtime environment will accept ssh connections. If ssh is disabled, the reason field will describe whether it is disabled globally, at the space level, or at the app level.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get SSH enabled for an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/actions/start" : {
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Start an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/actions/stop" : {
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Stop an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/actions/restart" : {
        "post" : {
          "description" : "This endpoint will synchronously stop and start an application. Unlike the start and stop actions, this endpoint will error if the app is not successfully stopped in the runtime.\n\nFor restarting applications without downtime, see the deployments resource.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Restart an app",
          "tags" : [ "Apps" ]
        }
      },
      "/v3/apps/{guid}/features" : {
        "get" : {
          "description" : "This endpoint retrieves the list of features for the specified app.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List app features",
          "tags" : [ "App Features" ]
        }
      },
      "/v3/apps/{guid}/features/{name}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an app feature",
          "tags" : [ "App Features" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update an app feature",
          "tags" : [ "App Features" ]
        }
      },
      "/v3/app_usage_events" : {
        "get" : {
          "description" : "Retrieve all app usage events the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List app usage events",
          "tags" : [ "App Usage Events" ]
        }
      },
      "/v3/app_usage_events/{guid}" : {
        "get" : {
          "description" : "Retrieve an app usage event.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin\"", "cloud_controller.admin_read_only", "cloud_controller.global_auditor" ]
          } ],
          "summary" : "Get an app usage event",
          "tags" : [ "App Usage Events" ]
        }
      },
      "/v3/app_usage_events/actions/destructively_purge_all_and_reseed" : {
        "post" : {
          "description" : "Destroys all existing events. Populates new usage events, one for each started app. All populated events will have a created_at value of current time. There is the potential race condition if apps are currently being started, stopped, or scaled. The seeded usage events will have the same guid as the app.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Purge and seed app usage events",
          "tags" : [ "App Usage Events" ]
        }
      },
      "/v3/audit_events" : {
        "get" : {
          "description" : "Retrieve all audit events the user has access to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List audit events",
          "tags" : [ "Audit Events" ]
        }
      },
      "/v3/audit_events/{guid}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor (cannot see events which occurred in orgs that the user does not belong to)\n* Space Auditor (cannot see events which occurred in orgs that the user does not belong to)\n* Space Developer (cannot see events which occurred in orgs that the user does not belong to)\n* Space Supporter (cannot see events which occurred in orgs that the user does not belong to)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an audit event",
          "tags" : [ "Audit Events" ]
        }
      },
      "/v3/builds" : {
        "get" : {
          "description" : "Retrieve all builds the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List builds",
          "tags" : [ "Builds" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a build",
          "tags" : [ "Builds" ]
        }
      },
      "/v3/builds/{guid}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a build",
          "tags" : [ "Builds" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a build",
          "tags" : [ "Builds" ]
        }
      },
      "/v3/apps/{guid}/builds" : {
        "get" : {
          "description" : "Retrieve all builds for the app.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List builds for an app",
          "tags" : [ "Apps", "Builds" ]
        }
      },
      "/v3/buildpacks" : {
        "get" : {
          "description" : "Retrieve all buildpacks the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List buildpacks",
          "tags" : [ "Buildpacks" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Create a buildpack",
          "tags" : [ "Buildpacks" ]
        }
      },
      "/v3/buildpacks/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Delete a buildpack",
          "tags" : [ "Buildpacks" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a buildpack",
          "tags" : [ "Buildpacks" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Update a buildpack",
          "tags" : [ "Buildpacks" ]
        }
      },
      "/v3/buildpacks/{guid}/upload" : {
        "post" : {
          "description" : "Upload a zip file containing a Cloud Foundry compatible buildpack. The file must be sent as part of a multi-part form.\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Upload buildpack bits",
          "tags" : [ "Buildpacks" ]
        }
      },
      "/v3/deployments" : {
        "get" : {
          "description" : "Retrieve all deployments the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List deployments",
          "tags" : [ "Deployments" ]
        },
        "post" : {
          "description" : "When you create a new deployment you can either provide a specific droplet or revision to deploy. If no revision or droplet is provided, the droplet associated with the app is deployed.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a deployment",
          "tags" : [ "Deployments" ]
        }
      },
      "/v3/deployments/{guid}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a deployment",
          "tags" : [ "Deployments" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a deployment",
          "tags" : [ "Deployments" ]
        }
      },
      "/v3/deployments/{guid}/actions/cancel" : {
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Cancel a deployment",
          "tags" : [ "Deployments" ]
        }
      },
      "/v3/domains" : {
        "get" : {
          "description" : "Retrieve all domains the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List domains",
          "tags" : [ "Domains" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Org Manager (when an organization relationship is provided)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a domain",
          "tags" : [ "Domains" ]
        }
      },
      "/v3/domains/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Org Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a domain",
          "tags" : [ "Domains" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Billing Manager (can only view domains without an organization relationship)\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a domain",
          "tags" : [ "Domains" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Org Manager (if domain is scoped to organization managed by the org manager)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a domain",
          "tags" : [ "Domains" ]
        }
      },
      "/v3/domains/{guid}/relationships/shared_organizations" : {
        "post" : {
          "description" : "This endpoint shares an organization-scoped domain to other organizations specified by a list of organization guids. This will allow any of the other organizations to use the organization-scoped domain.\n\n__Permitted Roles:__\n* Admin\n* Org Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Share a domain",
          "tags" : [ "Domains" ]
        }
      },
      "/v3/domains/{guid}/relationships/shared_organizations/{org_guid}" : {
        "delete" : {
          "description" : "This endpoint removes an organization from the list of organizations an organization-scoped domain is shared with. This prevents the organization from using the organization-scoped domain.\n\n__Permitted Roles:__\n* Admin\n* Org Manager (can be in either the domain's owning organization or the organization it has been shared to)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Unshare a domain",
          "tags" : [ "Domains" ]
        }
      },
      "/v3/droplets" : {
        "get" : {
          "description" : "Retrieve all droplets the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List droplets",
          "tags" : [ "Droplets" ]
        },
        "post" : {
          "description" : "This endpoint is only for creating or copying a droplet without a package. To create a droplet based on a package, see Create a build.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create/Copy a droplet",
          "tags" : [ "Droplets" ]
        }
      },
      "/v3/droplets/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a droplet",
          "tags" : [ "Droplets" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor (some fields are redacted)\n* Org Manager (some fields are redacted)\n* Space Auditor (some fields are redacted)\n* Space Developer\n* Space Manager (some fields are redacted)\n* Space Supporter (some fields are redacted)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a droplet",
          "tags" : [ "Droplets" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Build State Updater",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write", "cloud_controller.update_build_state" ]
          } ],
          "summary" : "Update a droplet",
          "tags" : [ "Droplets" ]
        }
      },
      "/v3/droplets/{guid}/download" : {
        "get" : {
          "description" : "Download a gzip compressed tarball file containing a Cloud Foundry compatible droplet. When using a remote blobstore, such as AWS, the response is a redirect to the actual location of the bits. If the client is automatically following redirects, then the OAuth token that was used to communicate with Cloud Controller will be relayed on the new redirect request. Some blobstores may reject the request in that case. Clients may need to follow the redirect without including[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Download droplet bits",
          "tags" : [ "Droplets" ]
        }
      },
      "/v3/droplets/{guid}/upload" : {
        "post" : {
          "description" : "Upload a gzip compressed tarball file containing a Cloud Foundry compatible droplet. The file must be sent as part of a multi-part form.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Upload droplet bits",
          "tags" : [ "Droplets" ]
        }
      },
      "/v3/apps/{guid}/droplets" : {
        "get" : {
          "description" : "Retrieve a list of droplets belonging to an app.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List droplets for an app",
          "tags" : [ "Apps", "Droplets" ]
        }
      },
      "/v3/environment_variable_groups/{name}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an environment variable group",
          "tags" : [ "Environment Variable Groups" ]
        },
        "patch" : {
          "description" : "Update the environment variable group. The variables given in the request will be merged with the existing environment variable group. Any requested variables with a value of null will be removed from the group. Environment variable names may not start with VCAP_. PORT is not a valid environment variable.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Update environment variable group",
          "tags" : [ "Environment Variable Groups" ]
        }
      },
      "/v3/feature_flags" : {
        "get" : {
          "description" : "Retrieve all feature_flags.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List feature flags",
          "tags" : [ "Feature Flags" ]
        }
      },
      "/v3/feature_flags/{name}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a feature flag",
          "tags" : [ "Feature Flags" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Update a feature flag",
          "tags" : [ "Feature Flags" ]
        }
      },
      "/v3/info" : {
        "get" : {
          "description" : "No authentication required.",
          "summary" : "Get platform info",
          "tags" : [ "Info" ]
        }
      },
      "/v3/info/usage_summary" : {
        "get" : {
          "description" : "This endpoint retrieves a high-level summary of usage across the entire Cloud Foundry installation.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor" ]
          } ],
          "summary" : "Get platform usage summary",
          "tags" : [ "Info" ]
        }
      },
      "/v3/isolation_segments" : {
        "get" : {
          "description" : "Retrieves all isolation segments to which the user has access. For admin, this is all the isolation segments in the system. For anyone else, this is the isolation segments in the allowed list for any organization to which the user belongs.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List isolation segments",
          "tags" : [ "Isolation Segments" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Create an isolation segment",
          "tags" : [ "Isolation Segments" ]
        }
      },
      "/v3/isolation_segments/{guid}" : {
        "delete" : {
          "description" : "An isolation segment cannot be deleted if it is entitled to any organization.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Delete an isolation segment",
          "tags" : [ "Isolation Segments" ]
        },
        "get" : {
          "description" : "Retrieve an isolation segment to which the user has access. For admin, this is any isolation segment in the system. For anyone else, this is an isolation segment in the allowed list for any organization to which the user belongs.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an isolation segment",
          "tags" : [ "Isolation Segments" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Update an isolation segment",
          "tags" : [ "Isolation Segments" ]
        }
      },
      "/v3/isolation_segments/{guid}/organizations" : {
        "get" : {
          "description" : "Retrieve the organizations entitled to the isolation segment. Return only the organizations the user has access to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Billing Manager\n* Org Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List organizations for isolation segment",
          "tags" : [ "Isolation Segments", "Organizations" ]
        }
      },
      "/v3/isolation_segments/{guid}/relationships/organizations" : {
        "get" : {
          "description" : "This endpoint lists the organizations entitled for the isolation segment. For an Admin, this will list all entitled organizations in the system. For any other user, this will list only the entitled organizations to which the user belongs.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List organizations relationship",
          "tags" : [ "Isolation Segments" ]
        },
        "post" : {
          "description" : "This endpoint entitles the specified organizations for the isolation segment. In the case where the specified isolation segment is the system-wide shared segment, and if an organization is not already entitled for any other isolation segment, then the shared isolation segment automatically gets assigned as the default for that organization.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Entitle organizations for an isolation segment",
          "tags" : [ "Isolation Segments" ]
        }
      },
      "/v3/isolation_segments/{guid}/relationships/organizations/{org_guid}" : {
        "delete" : {
          "description" : "This endpoint revokes the entitlement for the specified organization to the isolation segment. If the isolation segment is assigned to a space within an organization, the entitlement cannot be revoked. If the isolation segment is the organization’s default, the entitlement cannot be revoked.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Revoke entitlement to isolation segment for an organization",
          "tags" : [ "Isolation Segments" ]
        }
      },
      "/v3/isolation_segments/{guid}/relationships/spaces" : {
        "get" : {
          "description" : "This endpoint lists the spaces to which the isolation segment is assigned. For an Admin, this will list all associated spaces in the system. For an org manager, this will list only those associated spaces belonging to orgs for which the user is a manager. For any other user, this will list only those associated spaces to which the user has access.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List spaces relationship",
          "tags" : [ "Isolation Segments" ]
        }
      },
      "/v3/jobs/{guid}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a job",
          "tags" : [ "Jobs" ]
        }
      },
      "/v3/apps/{guid}/manifest" : {
        "get" : {
          "description" : "Generate a manifest for an app and its underlying processes.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Generate a manifest for an app",
          "tags" : [ "Apps", "Manifests" ]
        }
      },
      "/v3/spaces/{guid}/actions/apply_manifest" : {
        "post" : {
          "description" : "Apply changes specified in a manifest to the named apps and their underlying processes. The apps must reside in the space. These changes are additive and will not modify any unspecified properties or remove any existing environment variables, routes, or services.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Apply a manifest to a space",
          "tags" : [ "Manifests", "Spaces" ]
        }
      },
      "/v3/spaces/{guid}/manifest_diff" : {
        "post" : {
          "description" : "This endpoint returns a JSON representation of the difference between the provided manifest and the current state of a space.\n\n__Permitted Roles:__\n* Admin\n* Space Developers",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a manifest diff for a space (experimental)",
          "tags" : [ "Experimental", "Manifests", "Spaces" ]
        }
      },
      "/v3/organizations" : {
        "get" : {
          "description" : "Retrieve all organizations the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List organizations",
          "tags" : [ "Organizations" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Any with write access (if feature flag `user_org_creation` is set)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create an organization",
          "tags" : [ "Organizations" ]
        }
      },
      "/v3/organizations/{guid}" : {
        "delete" : {
          "description" : "When an organization is deleted, user roles associated with the organization will also be deleted.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Delete an organization",
          "tags" : [ "Organizations" ]
        },
        "get" : {
          "description" : "This endpoint retrieves the specified organization object.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an organization",
          "tags" : [ "Organizations" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Org Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update an organization",
          "tags" : [ "Organizations" ]
        }
      },
      "/v3/organizations/{guid}/domains" : {
        "get" : {
          "description" : "Retrieve all domains available in an organization for the current user. This will return unscoped domains (those without an owning organization), domains that are scoped to the given organization (owned by the given organization), and domains that have been shared with the organization.\n\nTo retrieve the default domain for an organization, use the get default domain endpoint.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List domains for an organization",
          "tags" : [ "Domains", "Organizations" ]
        }
      },
      "/v3/organizations/{guid}/domains/default" : {
        "get" : {
          "description" : "Retrieve the default domain for a given organization.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Billing Manager (can only view domains without an organization relationship)\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an organizations default domain",
          "tags" : [ "Domains", "Organizations" ]
        }
      },
      "/v3/organizations/{guid}/relationships/default_isolation_segment" : {
        "get" : {
          "description" : "Retrieve the default isolation segment for a given organization.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an organizations default isolation segment",
          "tags" : [ "Isolation Segments", "Organizations" ]
        },
        "patch" : {
          "description" : "Set the default isolation segment for a given organization. Only isolation segments that are entitled to the organization are eligible to be the default isolation segment.\n\n__Permitted Roles:__\n* Admin\n* Org Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Assign default isolation segment to an organization",
          "tags" : [ "Isolation Segments", "Organizations" ]
        }
      },
      "/v3/organizations/{guid}/usage_summary" : {
        "get" : {
          "description" : "This endpoint retrieves the specified organization object’s memory and app instance usage summary.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get usage summary for an organization",
          "tags" : [ "Organizations" ]
        }
      },
      "/v3/organizations/{guid}/users" : {
        "get" : {
          "description" : "Retrieve all users with a role in the specified organization.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List users of an organization",
          "tags" : [ "Organizations" ]
        }
      },
      "/v3/organization_quotas" : {
        "get" : {
          "description" : "This endpoint lists all organization quota resources.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager (response will only include guids of managed * organizations)\n* Org Auditor (response will only include guids of audited organizations)\n* Org Billing Manager (response will only include guids of billing-managed organizations)\n* Space Auditor (response will only include guids of parent organizations)\n* Space Developer (response will only include gu[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List organization quotas",
          "tags" : [ "Organization Quotas" ]
        },
        "post" : {
          "description" : "This endpoint creates a new organization quota, but does not assign it to a specific organization unless an organization GUID is provided in the relationships.organizations parameter.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Create an organization quota",
          "tags" : [ "Organization Quotas" ]
        }
      },
      "/v3/organization_quotas/{guid}" : {
        "delete" : {
          "description" : "Organization quotas cannot be deleted when applied to any organizations.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Delete an organization quota",
          "tags" : [ "Organization Quotas" ]
        },
        "get" : {
          "description" : "This endpoint gets an individual organization quota resource.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\nOrg Manager (response will only include guids of managed organizations)\n* Org Auditor (response will only include guids of audited organizations)\n* Org Billing Manager (response will only include guids of billing-managed organizations)\n* Space Auditor (response will only include guids of parent organizations)\n* Space Developer (response will only includ[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get an organization quota",
          "tags" : [ "Organization Quotas" ]
        },
        "patch" : {
          "description" : "This endpoint will only update the parameters specified in the request body. Any unspecified parameters will retain their existing values.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Update an organization quota",
          "tags" : [ "Organization Quotas" ]
        }
      },
      "/v3/organization_quotas/{guid}/relationships/organizations" : {
        "post" : {
          "description" : "This endpoint applies an organization quota to one or more organizations.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Apply an organization quota to an organization",
          "tags" : [ "Organization Quotas" ]
        }
      },
      "/v3/packages" : {
        "get" : {
          "description" : "Retrieve all packages the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List packages",
          "tags" : [ "Packages" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create/Copy a package",
          "tags" : [ "Packages" ]
        }
      },
      "/v3/packages/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a package",
          "tags" : [ "Packages" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a package",
          "tags" : [ "Packages" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a package",
          "tags" : [ "Packages" ]
        }
      },
      "/v3/packages/{guid}/droplets" : {
        "get" : {
          "description" : "Retrieve a list of droplets belonging to a package.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List droplets for a package",
          "tags" : [ "Droplets", "Packages" ]
        }
      },
      "/v3/packages/{guid}/upload" : {
        "post" : {
          "description" : "This upload endpoint takes a multi-part form requests for packages of type bits. The request requires either a .zip file uploaded under the bits field or a list of resource match objects under the resources field. These field may be used together.\n\nThe resources field in the request accepts the v2 resources object format.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Upload package bits",
          "tags" : [ "Packages" ]
        }
      },
      "/v3/packages/{guid}/download" : {
        "get" : {
          "description" : "This endpoint downloads the bits of an existing package.\n\nWhen using a remote blobstore, such as AWS, the response is a redirect to the actual location of the bits. If the client is automatically following redirects, then the OAuth token that was used to communicate with Cloud Controller will be replayed on the new redirect request. Some blobstores may reject the request in that case. Clients may need to follow the redirect without including the OAuth token.\n\n__Per[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Download package bits",
          "tags" : [ "Packages" ]
        }
      },
      "/v3/apps/{guid}/packages" : {
        "get" : {
          "description" : "Retrieve packages for an app that the user has access to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List packages for an app",
          "tags" : [ "Apps", "Packages" ]
        }
      },
      "/v3/processes" : {
        "get" : {
          "description" : "Retrieve all processes the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List processes",
          "tags" : [ "Processes" ]
        }
      },
      "/v3/processes/{guid}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor (some fields are redacted)\n* Org Manager (some fields are redacted)\n* Space Auditor (some fields are redacted)\n* Space Developer\n* Space Manager (some fields are redacted)\n* Space Supporter (some fields are redacted)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a process",
          "tags" : [ "Processes" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a process",
          "tags" : [ "Processes" ]
        }
      },
      "/v3/processes/{guid}/actions/scale" : {
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Scale a process",
          "tags" : [ "Processes" ]
        }
      },
      "/v3/processes/{guid}/instances/{index}" : {
        "delete" : {
          "description" : "Terminate an instance of a specific process. Health management will eventually restart the instance.\n\nThis allows a user to stop a single misbehaving instance of a process.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Terminate a process instance",
          "tags" : [ "Processes" ]
        }
      },
      "/v3/processes/{guid}/stats" : {
        "get" : {
          "description" : "Process stats are objects that represent the individual instances of a process.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor (some fields are redacted)\n* Org Manager (some fields are redacted)\n* Space Auditor (some fields are redacted)\n* Space Developer\n* Space Manager (some fields are redacted)\n* Space Supporter (some fields are redacted)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get stats for a process",
          "tags" : [ "Processes" ]
        }
      },
      "/v3/apps/{guid}/processes" : {
        "get" : {
          "description" : "Retrieves all processes belonging to an app.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List processes for app",
          "tags" : [ "Apps", "Processes" ]
        }
      },
      "/v3/apps/{guid}/processes/{type}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor (some fields are redacted)\n* Org Manager (some fields are redacted)\n* Space Auditor (some fields are redacted)\n* Space Developer\n* Space Manager (some fields are redacted)\n* Space Supporter (some fields are redacted)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a process of an app",
          "tags" : [ "Apps", "Processes" ]
        }
      },
      "/v3/apps/{guid}/processes/{type}/actions/scale" : {
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Scale a process of an app",
          "tags" : [ "Apps", "Processes" ]
        }
      },
      "/v3/apps/{guid}/processes/{type}/instances/{index}" : {
        "delete" : {
          "description" : "Terminate an instance of a specific process. Health management will eventually restart the instance.\n\nThis allows a user to stop a single misbehaving instance of a process.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Terminate a process instance of an app",
          "tags" : [ "Apps", "Processes" ]
        }
      },
      "/v3/apps/{guid}/processes/{type}/stats" : {
        "get" : {
          "description" : "Process stats are objects that represent the individual instances of a process.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor (some fields are redacted)\n* Org Manager (some fields are redacted)\n* Space Auditor (some fields are redacted)\n* Space Developer\n* Space Manager (some fields are redacted)\n* Space Supporter (some fields are redacted)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get stats for a process of an app",
          "tags" : [ "Apps", "Processes" ]
        }
      },
      "/v3/resource_matches" : {
        "post" : {
          "description" : "This endpoint returns a list of cached resources from the input list.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a resource match",
          "tags" : [ "Resource Matches" ]
        }
      },
      "/v3/revisions/{guid}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a revision",
          "tags" : [ "Revisions" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a revision",
          "tags" : [ "Revisions" ]
        }
      },
      "/v3/revisions/{guid}/environment_variables" : {
        "get" : {
          "description" : "Retrieve the environment variables that are associated with the revision.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Get environment variables for a revision",
          "tags" : [ "Revisions" ]
        }
      },
      "/v3/apps/{guid}/revisions" : {
        "get" : {
          "description" : "Retrieve revisions for an app the user has access to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List revisions for an app",
          "tags" : [ "Apps", "Revisions" ]
        }
      },
      "/v3/apps/{guid}/revisions/deployed" : {
        "get" : {
          "description" : "Retrieve deployed revisions for an app the user has access to. Deployed revisions are revisions that are linked to started processes in the app.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List deployed revisions for an app",
          "tags" : [ "Apps", "Revisions" ]
        }
      },
      "/v3/roles" : {
        "get" : {
          "description" : "This endpoint lists roles that the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List roles",
          "tags" : [ "Roles" ]
        },
        "post" : {
          "description" : "This endpoint creates a new role for a user in an organization or space.\n\nTo create an organization role you must be an admin or organization manager in the organization associated with the role.\n\nTo create a space role you must be an admin, an organization manager in the parent organization of the space associated with the role, or a space manager in the space associated with the role.\n\nFor a user to be assigned a space role, the user must already have an organi[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a role",
          "tags" : [ "Roles" ]
        }
      },
      "/v3/roles/{guid}" : {
        "delete" : {
          "description" : "This endpoint deletes an individual role.\n\n__Permitted Roles:__\n* Admin\n* Org Manager (can delete roles in managed organizations or spaces in those organizations)\n* Space Manager (can delete roles in managed spaces)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a role",
          "tags" : [ "Roles" ]
        },
        "get" : {
          "description" : "This endpoint gets an individual role resource.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager (can see roles in managed organizations or spaces in those organizations)\n* Org Auditor (can only see organization roles in audited organizations)\n* Org Billing Manager (can only see organization roles in billing-managed organizations)\n* Space Auditor (can see roles in audited spaces or parent organizations)\n* Space Developer (can see roles in developed[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a role",
          "tags" : [ "Roles" ]
        }
      },
      "/v3/routes" : {
        "get" : {
          "description" : "Retrieve all routes the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List routes",
          "tags" : [ "Routes" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a route",
          "tags" : [ "Routes" ]
        }
      },
      "/v3/routes/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a route",
          "tags" : [ "Routes" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a route",
          "tags" : [ "Routes" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a route",
          "tags" : [ "Routes" ]
        }
      },
      "/v3/routes/{guid}/destinations" : {
        "get" : {
          "description" : "Retrieve all destinations associated with a route.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List destinations for a route",
          "tags" : [ "Routes" ]
        },
        "patch" : {
          "description" : "Replaces all destinations for a route, removing any destinations not included in the provided list.\n\nIf using weighted destinations, all destinations provided here must have a weight specified, and all weights for this route must sum to 100. If not, all provided destinations must not have a weight. Mixing weighted and unweighted destinations for a route is not allowed.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Replace all destinations for a route",
          "tags" : [ "Routes" ]
        },
        "post" : {
          "description" : "Add one or more destinations to a route, preserving any existing destinations.\n\nNote that weighted destinations cannot be added with this endpoint. To add weighted destinations, replace all destinations for a route at once using the replace destinations endpoint.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Insert destinations for a route",
          "tags" : [ "Routes" ]
        }
      },
      "/v3/routes/{guid}/destinations/{destination_guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Remove destination from a route",
          "tags" : [ "Routes" ]
        },
        "patch" : {
          "description" : "This endpoint updates the protocol of a route destination (app, port and weight cannot be updated)\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a destination protocol for a route",
          "tags" : [ "Routes" ]
        }
      },
      "/v3/routes/{guid}/relationships/shared_spaces" : {
        "get" : {
          "description" : "Lists the spaces that the route has been shared to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List shared spaces relationship (experimental)",
          "tags" : [ "Experimental", "Routes" ]
        },
        "post" : {
          "description" : "This endpoint shares the route with the specified spaces. This allows users with read and write access in both the route's space and a shared space to bind a route to an app in the shared space. In order to share into a space the requesting user must have write permission in the target space.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Share a route with other spaces (experimental)",
          "tags" : [ "Experimental", "Routes" ]
        }
      },
      "/v3/routes/{guid}/relationships/shared_spaces/{space_guid}" : {
        "delete" : {
          "description" : "Unshares a route that was shared with another space.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Unshare a route that was shared with another space (experimental)",
          "tags" : [ "Experimental", "Routes" ]
        }
      },
      "/v3/routes/{guid}/relationships/space" : {
        "patch" : {
          "description" : "Transfers a the ownership of a route to a another space. Users must have write access for both spaces to perform this action. The original owning space will still retain access to the route as a shared space. To completely remove a space from a route, users will have to use unshare route.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Transfer ownership (experimental)",
          "tags" : [ "Experimental", "Routes" ]
        }
      },
      "/v3/apps/{guid}/routes" : {
        "get" : {
          "description" : "Retrieve all routes that have destinations that point to the given app.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List routes for an app",
          "tags" : [ "Apps", "Routes" ]
        }
      },
      "/v3/domains/{guid}/route_reservations" : {
        "get" : {
          "description" : "Check if a specific route for a domain exists, regardless of the user's visibility for the route in case the route belongs to a space the user does not belong to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor\n* Org Billing Manager (can only check if routes exist for a domain without an organization relationship\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Check reserved routes for a domain",
          "tags" : [ "Domains", "Routes" ]
        }
      },
      "/v3/spaces/{guid}/routes" : {
        "delete" : {
          "description" : "Deletes all routes in a space that are not mapped to any applications and not bound to any service instances.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete unmapped routes for a space",
          "tags" : [ "Routes", "Spaces" ]
        }
      },
      "/v3/security_groups" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor (can see globally enabled security groups)\n* Org Billing Manager (Can see globally enabled security groups)\n* Org Manager (can see globally enabled security groups or groups associated with a space they can see)\n* Space Auditor (can see globally enabled security groups or groups associated with a space they can see)\n* Space Developer (can see globally enabled security groups or groups associated with a [...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List security groups",
          "tags" : [ "Security Groups" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Create a security group",
          "tags" : [ "Security Groups" ]
        }
      },
      "/v3/security_groups/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Delete a security group",
          "tags" : [ "Security Groups" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor (can see globally enabled security groups)\n* Org Billing Manager (Can see globally enabled security groups)\n* Org Manager (can see globally enabled security groups or groups associated with a space they can see)\n* Space Auditor (can see globally enabled security groups or groups associated with a space they can see)\n* Space Developer (can see globally enabled security groups or groups associated with a [...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a security group",
          "tags" : [ "Security Groups" ]
        },
        "patch" : {
          "description" : "This endpoint will only update the parameters specified in the request body. Any unspecified parameters will retain their existing values.\n\nUpdates to the rules parameter will fully replace the current set of rules for the security group.\n\nUpdates to the globally_enabled parameter will be merged with the existing configuration. For example, an update to the globally_enabled.running parameter will not affect the globally_enabled.staging configuration.\n\n__Permitted[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Update a security group",
          "tags" : [ "Security Groups" ]
        }
      },
      "/v3/security_groups/{guid}/relationships/running_spaces" : {
        "post" : {
          "description" : "This endpoint binds one or more spaces to a security group with the running lifecycle.\n\nRunning app containers within these spaces will inherit the rules specified by this security group.\n\nApps within these spaces must be restarted for these changes to take effect.\n\nUnless a security group is globally-enabled, an admin must add it to a space for it to be visible for the org and space managers. Once it's visible, org and space managers can add it to additional spa[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Bind a running security group to spaces",
          "tags" : [ "Security Groups" ]
        }
      },
      "/v3/security_groups/{guid}/relationships/running_spaces/{space_guid}" : {
        "delete" : {
          "description" : "This endpoint removes a space from a security group with the running lifecycle.\n\nApps within this space must be restarted for these changes to take effect.\n\n__Permitted Roles:__\n* Admin\n* Space Manager (can unbind visible security groups from their spaces (visible groups are globally enabled security groups or groups associated with a space they can see))\n* Org Manager (can unbind visible security groups from their organizations spaces (visible groups are global[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Unbind a running security group from a space",
          "tags" : [ "Security Groups" ]
        }
      },
      "/v3/security_groups/{guid}/relationships/staging_spaces" : {
        "post" : {
          "description" : "This endpoint binds one or more spaces to a security group with the staging lifecycle.\n\nStaging app containers within these spaces will inherit the rules specified by this security group.\n\nApps within these spaces must be restaged for these changes to take effect.\n\nUnless a security group is globally-enabled, an admin must add it to a space for it to be visible for the org and space managers. Once it's visible, org and space managers can add it to additional spac[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Bind a staging security group to spaces",
          "tags" : [ "Security Groups" ]
        }
      },
      "/v3/security_groups/{guid}/relationships/staging_spaces/{space_guid}" : {
        "delete" : {
          "description" : "This endpoint removes a space from a security group with the staging lifecycle.\n\nApps within this space must be restaged for these changes to take effect.\n\n__Permitted Roles:__\n* Admin\n* Space Manager (can unbind visible security groups from their spaces (visible groups are globally enabled security groups or groups associated with a space they can see))\n* Org Manager (can unbind visible security groups from their organizations spaces (visible groups are globall[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Unbind a staging security group from a space",
          "tags" : [ "Security Groups" ]
        }
      },
      "/v3/spaces/{guid}/running_security_groups" : {
        "get" : {
          "description" : "This endpoint returns security groups that are enabled for running globally or at the space level for the given space.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager (can see globally-enabled security groups and groups associated with spaces in their managed organizations)\n* Space Auditor (can see globally-enabled security groups and groups associated with spaces where they have this role)\n* Space Developer (can see globally-enabled security groups[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List running security groups for a space",
          "tags" : [ "Security Groups", "Spaces" ]
        }
      },
      "/v3/spaces/{guid}/staging_security_groups" : {
        "get" : {
          "description" : "This endpoint returns security groups that are enabled for staging globally or at the space level for the given space.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager (can see globally-enabled security groups and groups associated with spaces in their managed organizations)\n* Space Auditor (can see globally-enabled security groups and groups associated with spaces where they have this role)\n* Space Developer (can see globally-enabled security groups[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List staging security groups for a space",
          "tags" : [ "Security Groups", "Spaces" ]
        }
      },
      "/v3/service_brokers" : {
        "get" : {
          "description" : "This endpoint retrieves the service brokers the user has access to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Space Developer (only space-scoped brokers)\n* Space Supporter (only space-scoped brokers)\n* Others (will receive an empty list)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List service brokers",
          "tags" : [ "Service Brokers" ]
        },
        "post" : {
          "description" : "This endpoint creates a new service broker and a job to synchronize the service offerings and service plans with those in the broker’s catalog. The Location header refers to the created job which syncs the broker with the catalog. See Service broker jobs for more information and limitations.\n\n__Permitted Roles:__\n* Admin\n* Space Developer (only space-scoped brokers)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a service broker",
          "tags" : [ "Service Brokers" ]
        }
      },
      "/v3/service_brokers/{guid}" : {
        "delete" : {
          "description" : "This endpoint creates a job to delete an existing service broker. The Location header refers to the created job.\n\n__Permitted Roles:__\n* Admin\n* Space Developer (only space-scoped brokers)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a service broker",
          "tags" : [ "Service Brokers" ]
        },
        "get" : {
          "description" : "This endpoint retrieves the service broker by GUID.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Space Developer (only space-scoped brokers)\n* Space Supporter (only space-scoped brokers)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a service broker",
          "tags" : [ "Service Brokers" ]
        },
        "patch" : {
          "description" : "This endpoint updates a service broker. Depending on the parameters specified, the endpoint may respond with a background job, and it may synchronize the service offerings and service plans with those in the broker’s catalog.\n\nWhen a service broker has a synchronization job in progress, only updates with metadata are permitted until the synchronization job is complete.\n\n__Permitted Roles:__\n* Admin\n* Space Developer (only space-scoped brokers)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a service broker",
          "tags" : [ "Service Brokers" ]
        }
      },
      "/v3/service_offerings" : {
        "get" : {
          "description" : "This endpoint retrieves the service offerings the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List service offerings",
          "tags" : [ "Service Offerings" ]
        }
      },
      "/v3/service_offerings/{guid}" : {
        "delete" : {
          "description" : "This endpoint deletes a service offering. This is typically used to remove orphan service offerings from the Cloud Foundry database when they have been removed from the service broker catalog, or when the service broker has been removed.\n\nNote that this operation only affects the Cloud Foundry database, and no attempt is made to contact the service broker.\n\n__Permitted Roles:__\n* Admin\n* Space Developer (only service offerings from space-scoped brokers)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a service offering",
          "tags" : [ "Service Offerings" ]
        },
        "get" : {
          "description" : "This endpoint retrieves the service offering by GUID.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a service offering",
          "tags" : [ "Service Offerings" ]
        },
        "patch" : {
          "description" : "This endpoint updates a service offering with labels and annotations.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Update a service offering",
          "tags" : [ "Service Offerings" ]
        }
      },
      "/v3/service_plans" : {
        "get" : {
          "description" : "This endpoint retrieves the service plans the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List service plans",
          "tags" : [ "Service Plans" ]
        }
      },
      "/v3/service_plans/{guid}" : {
        "delete" : {
          "description" : "This endpoint deletes a service plan. This is used to remove service plans from the Cloud Foundry database when they are no longer provided by the service broker.\n\n__Permitted Roles:__\n* Admin\n* Space Developer (only service plans from space-scoped brokers)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a service plan",
          "tags" : [ "Service Plans" ]
        },
        "get" : {
          "description" : "This endpoint retrieves the service plan by GUID.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a service plan",
          "tags" : [ "Service Plans" ]
        },
        "patch" : {
          "description" : "This endpoint updates a service plan with labels and annotations.\n\n__Permitted Roles:__\n* Admin\n* Space Developer (only for service plans from space-scoped brokers)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a service plan",
          "tags" : [ "Service Plans" ]
        }
      },
      "/v3/service_plans/{guid}/visibility" : {
        "get" : {
          "description" : "This endpoint retrieves the service plan visibility for a given plan.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a service plan visibility",
          "tags" : [ "Service Plan Visibility" ]
        },
        "patch" : {
          "description" : "This endpoint updates a service plan visibility. It behaves similar to the POST service plan visibility endpoint but this endpoint will replace the existing list of organizations when the service plan is organization visible.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Update a service plan visibility",
          "tags" : [ "Service Plan Visibility" ]
        },
        "post" : {
          "description" : "This endpoint applies a service plan visibility. It behaves similar to the PATCH service plan visibility endpoint but this endpoint will append to the existing list of organizations when the service plan is organization visible.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Apply a service plan visibility",
          "tags" : [ "Service Plan Visibility" ]
        }
      },
      "/v3/service_plans/{guid}/visibility/{organization_guid}" : {
        "delete" : {
          "description" : "This endpoint removes an organization from a service plan visibility list of organizations. It is only defined for service plans which are org-restricted. It will fail with a HTTP status code of 422 for any other visibility type (e.g. Public).\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Remove organization from a service plan visibility",
          "tags" : [ "Service Plan Visibility" ]
        }
      },
      "/v3/service_instances" : {
        "get" : {
          "description" : "This endpoint retrieves the service instances the user has access to, including access granted by service instance sharing.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List service instances",
          "tags" : [ "Service Instances" ]
        },
        "post" : {
          "description" : "This endpoint creates a new service instance. Service instances can be of type managed or user-provided, and the required parameters are different for each type. User provided service instances do not require interactions with service brokers.\n\nIf failures occur when creating managed service instances, the API might execute orphan mitigation steps accordingly to cases outlined in the OSBAPI specification\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a service instance",
          "tags" : [ "Service Instances" ]
        }
      },
      "/v3/service_instances/{guid}" : {
        "delete" : {
          "description" : "This endpoint deletes a service instance and any associated service credential bindings or service route bindings. The service instance is removed from all spaces where it is available.\n\nUser provided service instances do not require interactions with service brokers, therefore the API will respond synchronously to the delete request.\n\nFor managed service instances, the API will respond asynchronously. If a service credential binding or service route binding cannot[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a service instance",
          "tags" : [ "Service Instances" ]
        },
        "get" : {
          "description" : "This endpoint retrieves the service instance by GUID.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a service instance",
          "tags" : [ "Service Instances" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a service instance",
          "tags" : [ "Service Instances" ]
        }
      },
      "/v3/service_instances/{guid}/credentials" : {
        "get" : {
          "description" : "Retrieves the credentials for a user-provided service instance. This endpoint is not available for managed service instances.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Get credentials for a user-provided service instance",
          "tags" : [ "Service Instances" ]
        }
      },
      "/v3/service_instances/{guid}/parameters" : {
        "get" : {
          "description" : "Queries the Service Broker for the parameters associated with this service instance. The broker catalog must have enabled the instances_retrievable feature for the Service Offering.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get parameters for a managed service instance",
          "tags" : [ "Service Instances" ]
        }
      },
      "/v3/service_instances/{guid}/permissions" : {
        "get" : {
          "description" : "Get the current user's permissions for the given service instance. If a user can get a service instance then they can read it. Users who can update a service instance can manage it.\n\nThis endpoint's primary purpose is to enable third-party service dashboards to determine the permissions of a given Cloud Foundry user that has authenticated with the dashboard via single sign-on (SSO). For more information, see the Cloud Foundry documentation on Dashboard Single Sign-On[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get permissions for a service instance",
          "tags" : [ "Service Instances" ]
        }
      },
      "/v3/service_instances/{guid}/relationships/shared_spaces" : {
        "get" : {
          "description" : "This endpoint lists the spaces that the service instance has been shared to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List shared spaces relationship",
          "tags" : [ "Service Instances" ]
        },
        "post" : {
          "description" : "This endpoint shares the service instance with the specified spaces. In order to share into a space the requesting user must be a space developer in the target space.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Share a service instance to other spaces",
          "tags" : [ "Service Instances" ]
        }
      },
      "/v3/service_instances/{guid}/relationships/shared_spaces/{space_guid}" : {
        "delete" : {
          "description" : "This endpoint unshares the service instance from the specified space. This will automatically unbind any applications bound to this service instance in the specified space. Unsharing a service instance from a space will not delete any service keys.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Unshare a service instance from another space",
          "tags" : [ "Service Instances" ]
        }
      },
      "/v3/service_instances/{guid}/relationships/shared_spaces/usage_summary" : {
        "get" : {
          "description" : "This endpoint returns the number of bound apps in spaces where the service instance has been shared to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get usage summary in shared spaces",
          "tags" : [ "Service Instances" ]
        }
      },
      "/v3/service_credential_bindings" : {
        "get" : {
          "description" : "This endpoint retrieves the service credential bindings the user has access to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List service credential bindings",
          "tags" : [ "Service Credential Bindings" ]
        },
        "post" : {
          "description" : "This endpoint creates a new service credential binding. Service credential bindings can be of type app or key; key is only valid for managed service instances.\n\nIf failures occur when creating a service credential binding for a managed service instances, the API might execute orphan mitigation steps accordingly to cases outlined in the OSBAPI specification\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter (only allowed to create bindings of type [...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a service credential binding",
          "tags" : [ "Service Credential Bindings" ]
        }
      },
      "/v3/service_credential_bindings/{guid}" : {
        "delete" : {
          "description" : "This endpoint deletes a service credential binding. When deleting credential bindings originated from user provided service instances, the delete operation does not require interactions with service brokers, therefore the API will respond synchronously to the delete request.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter (only allowed to delete bindings of type app)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a service credential binding",
          "tags" : [ "Service Credential Bindings" ]
        },
        "get" : {
          "description" : "This endpoint retrieves the service credential binding by GUID.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a service credential binding",
          "tags" : [ "Service Credential Bindings" ]
        },
        "patch" : {
          "description" : "This endpoint updates a service credential binding with labels and annotations.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a service credential binding",
          "tags" : [ "Service Credential Bindings" ]
        }
      },
      "/v3/service_credential_bindings/{guid}/details" : {
        "get" : {
          "description" : "This endpoint retrieves the service credential binding details.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Get details from a service credential binding",
          "tags" : [ "Service Credential Bindings" ]
        }
      },
      "/v3/service_credential_bindings/{guid}/parameters" : {
        "get" : {
          "description" : "Queries the Service Broker for the parameters associated with this service credential binding. The broker catalog must have enabled the bindings_retrievable feature for the Service Offering. Check the Service Offering object for the value of this feature flag. This endpoint is not available for User-Provided Service Instances.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Get parameters for a service credential binding",
          "tags" : [ "Service Credential Bindings" ]
        }
      },
      "/v3/service_route_bindings" : {
        "get" : {
          "description" : "This endpoint retrieves the service route bindings the user has access to.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List service route bindings",
          "tags" : [ "Service Route Bindings" ]
        },
        "post" : {
          "description" : "This endpoint creates a new route service binding. The service instance and the route must be in the same space.\n\nTo bind a route to a user-provided service instance, the service instance must have the route_service_url property set.\n\nTo bind a route to a managed service instance, the service offering must be bindable, and the service offering must have route_forwarding set in the requires property.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Suppo[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a service route binding",
          "tags" : [ "Service Route Bindings" ]
        }
      },
      "/v3/service_route_bindings/{guid}" : {
        "delete" : {
          "description" : "This endpoint deletes a service route binding. When deleting route bindings originating from user provided service instances, the delete operation does not require interactions with service brokers, therefore the API will respond synchronously to the delete request. Consequently, deleting route bindings from managed service instances responds with a job which can be used to track the progress of the delete operation.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a service route binding",
          "tags" : [ "Service Route Bindings" ]
        },
        "get" : {
          "description" : "This endpoint retrieves the service route binding by GUID.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a service route binding",
          "tags" : [ "Service Route Bindings" ]
        },
        "patch" : {
          "description" : "This endpoint updates a service route binding with labels and annotations.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a service route binding",
          "tags" : [ "Service Route Bindings" ]
        }
      },
      "/v3/service_route_bindings/{guid}/parameters" : {
        "get" : {
          "description" : "Queries the Service Broker for the parameters associated with this service route binding. The broker catalog must have enabled the bindings_retrievable feature for the Service Offering. Check the Service Offering object for the value of this feature flag. This endpoint is not available for User-Provided Service Instances.\n\n__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.read" ]
          } ],
          "summary" : "Get parameters for a route binding",
          "tags" : [ "Service Route Bindings" ]
        }
      },
      "/v3/service_usage_events" : {
        "get" : {
          "description" : "Retrieve all service usage events the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List service usage events",
          "tags" : [ "Service Usage Events" ]
        }
      },
      "/v3/service_usage_events/{guid}" : {
        "get" : {
          "description" : "Retrieve a service usage event.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor" ]
          } ],
          "summary" : "Get a service usage event",
          "tags" : [ "Service Usage Events" ]
        }
      },
      "/v3/service_usage_events/actions/destructively_purge_all_and_reseed" : {
        "post" : {
          "description" : "Destroys all existing events. Populates new usage events, one for each existing service instance. All populated events will have a created_at value of current time. There is the potential race condition if service instances are currently being created or deleted. The seeded usage events will have the same guid as the service instance.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Purge and seed service usage events",
          "tags" : [ "Service Usage Events" ]
        }
      },
      "/v3/apps/{guid}/sidecars" : {
        "get" : {
          "description" : "Retrieves all sidecars associated with a app.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List sidecars for app",
          "tags" : [ "Apps", "Sidecars" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a sidecar associated with an app",
          "tags" : [ "Apps", "Sidecars" ]
        }
      },
      "/v3/processes/{guid}/sidecars" : {
        "get" : {
          "description" : "Retrieves all sidecars associated with a process.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List sidecars for process",
          "tags" : [ "Processes", "Sidecars" ]
        }
      },
      "/v3/sidecars/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a sidecar",
          "tags" : [ "Sidecars" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a sidecar",
          "tags" : [ "Sidecars" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a sidecar",
          "tags" : [ "Sidecars" ]
        }
      },
      "/v3/spaces" : {
        "get" : {
          "description" : "Retrieve all spaces the user has access to.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List spaces",
          "tags" : [ "Spaces" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Org Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a space",
          "tags" : [ "Spaces" ]
        }
      },
      "/v3/spaces/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Org Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a space",
          "tags" : [ "Spaces" ]
        },
        "get" : {
          "description" : "This endpoint retrieves the specified space object.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a space",
          "tags" : [ "Spaces" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Org Manager\n* Space Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a space",
          "tags" : [ "Spaces" ]
        }
      },
      "/v3/spaces/{guid}/relationships/isolation_segment" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get assigned isolation segment",
          "tags" : [ "Spaces" ]
        },
        "patch" : {
          "description" : "This endpoint assigns an isolation segment to the space. The isolation segment must be entitled to the space’s parent organization.\n\n__Permitted Roles:__\n* Admin\n* Org Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Manage isolation segment",
          "tags" : [ "Spaces" ]
        }
      },
      "/v3/spaces/{guid}/users" : {
        "get" : {
          "description" : "Retrieve all users with a role in the specified space.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List users for a space",
          "tags" : [ "Spaces" ]
        }
      },
      "/v3/spaces/{guid}/features" : {
        "get" : {
          "description" : "This endpoint retrieves the list of features for the specified space. Currently, the only feature on spaces is the SSH feature.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List space features",
          "tags" : [ "Space Features" ]
        }
      },
      "/v3/spaces/{guid}/features/{name}" : {
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager\n* Space Auditor\n* Space Developer\n* Space Manager\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a space feature",
          "tags" : [ "Space Features" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Org Manager\n* Space Manager",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a space feature",
          "tags" : [ "Space Features" ]
        }
      },
      "/v3/space_quotas" : {
        "get" : {
          "description" : "This endpoint lists all space quota resources that the user has permission to view (see getting a space quota).\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List space quotas",
          "tags" : [ "Space Quotas" ]
        },
        "post" : {
          "description" : "This endpoint creates a new space quota scoped to a specific organization.\n\n__Permitted Roles:__\n* Admin\n* Org Manager (can create space quotas in their managed organizations)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a space quota",
          "tags" : [ "Space Quotas" ]
        }
      },
      "/v3/space_quotas/{guid}" : {
        "delete" : {
          "description" : "Space quotas cannot be deleted when applied to any spaces.\n\n__Permitted Roles:__\n* Admin\n* Org Manager (can delete space quotas in their managed organizations)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Delete a space quota",
          "tags" : [ "Space Quotas" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Manager (can only query space quotas owned by affiliated organizations)\n* Space Auditor (can only query space quotas applied to affiliated spaces)\n* Space Developer (can only query space quotas applied to affiliated spaces)\n* Space Manager (can only query space quotas applied to affiliated spaces)\n* Space Supporter (can only query space quotas applied to affiliated spaces)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a space quota",
          "tags" : [ "Space Quotas" ]
        },
        "patch" : {
          "description" : "This endpoint will only update the parameters specified in the request body. Any unspecified parameters will retain their existing values.\n\n__Permitted Roles:__\n* Admin\n* Org Manager (can delete space quotas within their managed organizations)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a space quota",
          "tags" : [ "Space Quotas" ]
        }
      },
      "/v3/space_quotas/{guid}/relationships/spaces" : {
        "post" : {
          "description" : "This endpoint applies a space quota to one or more spaces.\n\n__Permitted Roles:__\n* Admin\n* Org Manager (can apply space quotas to spaces within their managed organizations)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Apply a space quota to a space",
          "tags" : [ "Space Quotas" ]
        }
      },
      "/v3/space_quotas/{guid}/relationships/spaces/{space_guid}" : {
        "delete" : {
          "description" : "This endpoint removes a space quota from a space.\n\n__Permitted Roles:__\n* Admin\n* Org Manager (can remove space quotas from spaces within their managed organizations)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Remove a space quota from a space",
          "tags" : [ "Space Quotas" ]
        }
      },
      "/v3/stacks" : {
        "get" : {
          "description" : "Retrieve all stacks.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List stacks",
          "tags" : [ "Stacks" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Create a stack",
          "tags" : [ "Stacks" ]
        }
      },
      "/v3/stacks/{guid}" : {
        "delete" : {
          "description" : "__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Delete a stack",
          "tags" : [ "Stacks" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a stack",
          "tags" : [ "Stacks" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a stack",
          "tags" : [ "Stacks" ]
        }
      },
      "/v3/stacks/{guid}/apps" : {
        "get" : {
          "description" : "Retrieve all apps using a given stack.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List apps on a stack",
          "tags" : [ "Stacks" ]
        }
      },
      "/v3/tasks" : {
        "get" : {
          "description" : "Retrieve all tasks the user has access to. The command field is excluded in the response.\n\n__Permitted Roles:__\n* All Roles",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List tasks",
          "tags" : [ "Tasks" ]
        }
      },
      "/v3/tasks/{guid}" : {
        "get" : {
          "description" : "Retrieve a specific task. The command field may be excluded in the response based on the user’s role.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor (command field redacted)\n* Org Manager (command field redacted)\n* Space Auditor (command field redacted)\n* Space Developer\n* Space Manager (command field redacted)\n* Space Supporter (command field redacted)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a task",
          "tags" : [ "Tasks" ]
        },
        "patch" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Update a task",
          "tags" : [ "Tasks" ]
        }
      },
      "/v3/tasks/{guid}/actions/cancel" : {
        "post" : {
          "description" : "Cancels a running task.\n\nCanceled tasks will initially be in state CANCELING and will move to state FAILED once the cancel request has been processed.\n\nCancel requests are idempotent and will be processed according to the state of the task when the request is executed.\n\nCanceling a task that is in SUCCEEDED or FAILED state will return an error.\n\n__Permitted Roles:__\n* Admin\n* Space Developer\n* Space Supporter",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Cancel a task",
          "tags" : [ "Tasks" ]
        }
      },
      "/v3/apps/{guid}/tasks" : {
        "get" : {
          "description" : "Retrieve tasks for an app the user has access to. The command field may be excluded in the response based on the user’s role.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor (command field redacted)\n* Org Manager (command field redacted)\n* Space Auditor (command field redacted)\n* Space Developer\n* Space Manager (command field redacted)\n* Space Supporter (command field redacted)",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List tasks for an app",
          "tags" : [ "Tasks" ]
        },
        "post" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Space Developer",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.write" ]
          } ],
          "summary" : "Create a task",
          "tags" : [ "Tasks" ]
        }
      },
      "/v3/users" : {
        "get" : {
          "description" : "Retrieve all users that the current user can see.\n\n__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor (can only view users affiliated with their org)\n* Org Billing Manager (can only view users affiliated with their org)\n* Org Manager (can only view users affiliated with their org)\n* Space Auditor (can only view users affiliated with their org)\n* Space Developer (can only view users affiliated with their org)\n* Space Manager (can only view users affil[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "List users",
          "tags" : [ "Users" ]
        },
        "post" : {
          "description" : "Creating a user requires one value, a GUID. This creates a user in the Cloud Controller database.\n\nGenerally, the GUID should match the GUID of an already-created user in the UAA database, though this is not required.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Create a user",
          "tags" : [ "Users" ]
        }
      },
      "/v3/users/{guid}" : {
        "delete" : {
          "description" : "All roles associated with a user will be deleted if the user is deleted.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Delete a user",
          "tags" : [ "Users" ]
        },
        "get" : {
          "description" : "__Permitted Roles:__\n* Admin\n* Global Auditor\n* Org Auditor (can only view users affiliated with their org)\n* Org Billing Manager (can only view users affiliated with their org)\n* Org Manager (can only view users affiliated with their org)\n* Space Auditor (can only view users affiliated with their org)\n* Space Developer (can only view users affiliated with their org)\n* Space Manager (can only view users affiliated with their org)\n* Space Supporter (can only vi[...]",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin", "cloud_controller.admin_read_only", "cloud_controller.global_auditor", "cloud_controller.read" ]
          } ],
          "summary" : "Get a user",
          "tags" : [ "Users" ]
        },
        "patch" : {
          "description" : "Update a user's metadata.\n\n__Permitted Roles:__\n* Admin",
          "security" : [ {
            "uaa" : [ "cloud_controller.admin" ]
          } ],
          "summary" : "Update a user",
          "tags" : [ "Users" ]
        }
      }
    },
    "components" : {
      "securitySchemes" : {
        "uaa" : {
          "description" : "Authenticate with the Cloud Foundry UAA service, using the Resource Owner Password flow. \n\nIf two-factor authentication (2FA) is activated on the account, you have to enter your password followed by a one-time TOTP (Time-based One-Time Password) token. \n\n*Hint*: In case you don't have dedicated client credentials at hand, you can use the defaults of the cloud foundry cli. Just enter `cf` as `client_id`, leave `client_secret` blank.",
          "flows" : {
            "password" : {
              "scopes" : {
                "cloud_controller.admin" : "This scope provides read and write access to all resources",
                "cloud_controller.admin_read_only" : "This scope provides read only access to all resources",
                "cloud_controller.global_auditor" : "This scope provides read only access to all resources except secrets (such as environment variables)",
                "cloud_controller.read" : "This scope provides read access to resources based on user roles",
                "cloud_controller.write" : "This scope provides write access to resources based on user roles",
                "cloud_controller.update_build_state" : "This scope allows its bearer to update the state of a build; currently only used when updating builds",
                "cloud_controller_service_permissions.read" : "This scope provides read only access for service instance permissions"
              },
              "tokenUrl" : "https://uaa.cf.eu12.hana.ondemand.com/oauth/token"
            }
          },
          "type" : "oauth2"
        }
      }
    }
  }